-- MySQL Script generated by MySQL Workbench
-- Tue Sep  9 14:51:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema simple-library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema simple-library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simple-library` DEFAULT CHARACTER SET utf8 ;
USE `simple-library` ;

-- -----------------------------------------------------
-- Table `simple-library`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple-library`.`genre` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple-library`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple-library`.`books` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `author` VARCHAR(100) NOT NULL,
  `release` SMALLINT NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `rating` TINYINT UNSIGNED NULL,
  `image_path` VARCHAR(100) NOT NULL,
  `genre_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `genre_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `books_genre_idx` (`genre_id` ASC),
  CONSTRAINT `books_genre`
    FOREIGN KEY (`genre_id`)
    REFERENCES `simple-library`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple-library`.`content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple-library`.`content` (
  `books_id` INT UNSIGNED NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`books_id`),
  CONSTRAINT `content_books1`
    FOREIGN KEY (`books_id`)
    REFERENCES `simple-library`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
